---
abstract: 'A Perl interface to the bit.ly API'
author:
  - 'Yuki Shibazaki <shibayu36@gmail.com>'
build_requires:
  Exporter: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  IO::Prompt: 0
  Path::Class: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
  YAML::Syck: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Bitly
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  JSON: 0
  LWP::UserAgent: 0
  UNIVERSAL::require: 0
  URI: 0
  URI::QueryParam: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
